- name: ..... create aggregate "{{ item.aggregate_name }}"

  netapp.ontap.na_ontap_aggregate:

    hostname: "{{ cluster_hostname }}"
    username: "{{ cluster_username }}"
    password: "{{ cluster_password }}"
    https: true
    validate_certs: false

    name: "{{ item.aggregate_name }}"
    nodes: "{{ item.aggregate_node }}"
    state: present
    service_state: online
    disk_count: "{{ item.aggregate_disk_count }}"
    raid_size: "{{ item.aggregate_raid_size }}"
    raid_type: "{{ omit if item.aggregate_raid_type.lower() is search('raid0') else item.aggregate_raid_type }}"
    is_mirrored: "{{ item.mirrored }}"
   
    wait_for_online: true
