- name: Assign Disks

  netapp.ontap.na_ontap_disks:

    hostname: "{{ cluster_hostname }}"
    username: "{{ cluster_username }}"
    password: "{{ cluster_password }}"
    https: true
    validate_certs: false
    
    node: "{{ item.node_name }}"
    disk_count: "{{ omit if item.diskcount == none }}"
