- name: ..... create CIFS Server {{ item.cifs_server_name }}

  netapp.ontap.na_ontap_cifs_server:

    hostname: "{{ cluster_hostname }}"
    username: "{{ cluster_username }}"
    password: "{{ cluster_password }}"
    https: true
    validate_certs: false
    ontapi: "{{ ontap_facts.ontap_version }}"

    state: present
    vserver: "{{ item.svm_name }}"
    domain: "{{ item.domain }}"
    cifs_server_name: "{{ item.cifs_server_name }}"
    force: "{{ 'false' if item.force is not defined else item.force }}"
    admin_password: "{{ admin_password }}"
    admin_user_name: "{{ admin_username }}"
    ou: "{{ item.ou | default(omit) }}"
    service_state: started
