- name: Date & Time

  nnetapp.ontap.a_ontap_command:

    hostname: "{{ cluster_hostname }}"
    username: "{{ cluster_username }}"
    password: "{{ cluster_password }}"
    https: true
    validate_certs: false
    
    command:
