- name: ..... create job schedules

  netapp.ontap.na_ontap_job_schedule:

    hostname: "{{ cluster_hostname }}"
    username: "{{ cluster_username }}"
    password: "{{ cluster_password }}"
    https: true
    validate_certs: false

    name: "{{ item.job_name }}"
    state: present
    job_hours: "{{ item.job_hours }}"
    job_minutes: "{{ item.job_minutes }}"

  with_items: "{{ job_schedules }}"

  when:
    - job_schedules != none

- name: ..... create efficiency policies

  netapp.ontap.na_ontap_efficiency_policy:

    hostname: "{{ cluster_hostname }}"
    username: "{{ cluster_username }}"
    password: "{{ cluster_password }}"
    https: true
    validate_certs: false

    state: present
    enabled: true
    vserver: "{{ cluster_name }}"
    policy_name: "{{ item.policy_name}}"
    policy_type: "{{ item.type }}"
    schedule: "{{ item.schedule }}"
    qos_policy: "{{ item.qos_policy }}"


  with_items: "{{ efficiency_policies }}"

  when:
    - efficiency_policies != none
