- name: ..... Enable Cluster HA

  na_ontap_cluster_ha:

    hostname: "{{ cluster_hostname }}"
    username: "{{ cluster_username }}"
    password: "{{ cluster_password }}"
    https: true
    validate_certs: false
    
    state: present
