- name: ..... add licenses

  na_ontap_license:

    hostname: "{{ cluster_hostname }}"
    username: "{{ cluster_username }}"
    password: "{{ cluster_password }}"
    state: present
    https: true
    validate_certs: false
    
    license_codes: "{{ license_codes }}"
