- name: ..... create LIF "{{ item.lif_name }}"

  netapp.ontap.na_ontap_interface:

    hostname: "{{ cluster_hostname }}"
    username: "{{ cluster_username }}"
    password: "{{ cluster_password }}"
    https: true
    validate_certs: false

    state: present
    interface_name: "{{ item.lif_name }}"
    home_port: "{{ item.home_port }}"
    home_node: "{{ item.home_node }}"
    role: data
    protocols: "{{ item.protocol }}"
    admin_status: up
    is_auto_revert: "{{ 'true' if item.protocol.lower() is not search('iscsi') else omit }}"
    address: "{{ item.address }}"
    netmask: "{{ item.netmask }}"
    vserver: "{{ item.svm_name }}"
