- name: ..... create LUN "{{ item.lun_name }}"

  na_ontap_lun:

    hostname: "{{ cluster_hostname }}"
    username: "{{ cluster_username }}"
    password: "{{ cluster_password }}"
    https: true
    validate_certs: false

    state: present
    name: "{{ item.lun_name }}"
    flexvol_name: "{{ item.volume_name }}"
    vserver: "{{ item.svm_name }}"
    size: "{{ lookup('template', 'convert2bytes.j2')  | int }}"
    size_unit: b
    ostype: "{{ item.ostype }}"
    space_reserve: false
    space_allocation: true

- name: ..... map LUN "{{ item.lun_name }}"

  na_ontap_lun_map:

    hostname: "{{ cluster_hostname }}"
    username: "{{ cluster_username }}"
    password: "{{ cluster_password }}"
    https: true
    validate_certs: false

    state: present
    initiator_group_name: "{{ item.igroup }}"
    path: "/vol/{{ item.volume_name }}/{{ item.lun_name }}"
    lun_id: "{{ item.lunid | default(omit) }}"
    vserver: "{{ item.svm_name }}"
