- name: ...set MOTD - {{ vserver_name }}

  netapp.ontap.na_ontap_motd: 

    hostname: "{{ cluster_hostname }}"
    username: "{{ cluster_username }}"
    password: "{{ cluster_password }}"
    https: true
    validate_certs: false
    
    motd_message: "{{ motd }}"
    vserver: "{{ vserver_name }}"
    state: present
