- name: ..... add NTP server

  netapp.ontap.na_ontap_ntp:

    hostname: "{{ cluster_hostname }}"
    username: "{{ cluster_username }}"
    password: "{{ cluster_password }}"
    https: true
    validate_certs: false
    
    state: present
    server_name: "{{ item }}"
    version: auto
