- name: ..... collect ONTAP Info

  netapp.ontap.na_ontap_rest_info:

    hostname: "{{ cluster_hostname }}"
    username: "{{ cluster_username }}"
    password: "{{ cluster_password }}"
    https: true
    validate_certs: false
    
    use_python_keys: true
      
    gather_subset: 
      - cluster
      - cluster/nodes
      - storage/luns
    
    fields: '*'

  register: details

- name: ..... retrieve cluster name

  set_fact:
    current_cluster_name: "{{ details.ontap_info.cluster.name }}"

- name: ..... retrieve node names

  set_fact:
    node_list: "{{ node_list | default([]) + [ {'node_name': item.name} ] }}"
  with_items: "{{ details.ontap_info.cluster_nodes.records }}"
  loop_control:
    label: "{{ item.name}}"

