- name: ..... rename root aggregate from "{{ item.root_aggr }} to {{ item.new_root_aggr }}"

  netapp.ontap.na_ontap_aggregate:

    hostname: "{{ cluster_hostname }}"
    username: "{{ cluster_username }}"
    password: "{{ cluster_password }}"
    https: true
    validate_certs: false

    name: "{{ item.new_root_aggr }}"
    from_name: "{{ item.root_aggr }}"
    state: present
