
- name: ..... service processor on "{{ item.node_name }}"

  netapp.ontap.na_ontap_service_processor_network:

    hostname: "{{ cluster_hostname }}"
    username: "{{ cluster_username }}"
    password: "{{ cluster_password }}"
    https: true
    validate_certs: false
    
    is_enabled: true
    node: "{{ item.node_name }}"
    address_type: ipv4
    state: present
    ip_address: "{{ item.sp_ip }}"
    netmask: "{{ item.sp_netmask }}"
    gateway_ip_address: "{{ item.sp_gateway }}"
